This is makeindex, version 2.15 [TeX Live 2015/dev] (kpathsea + Thai support).
Scanning style file ./documento.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file documento.acn....done (6 entries accepted, 0 rejected).
Sorting entries....done (17 comparisons).
Generating output file documento.acr....done (15 lines written, 0 warnings).
Output written in documento.acr.
Transcript written in documento.alg.
