# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/synth_design_constrs.xdc

# Block Designs: bd/mb_design/mb_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design || ORIG_REF_NAME==mb_design} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_0/mb_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_0 || ORIG_REF_NAME==mb_design_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_v10_0/mb_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_dlmb_v10_0 || ORIG_REF_NAME==mb_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_v10_0/mb_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_ilmb_v10_0 || ORIG_REF_NAME==mb_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_dlmb_bram_if_cntlr_0/mb_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_ilmb_bram_if_cntlr_0/mb_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_lmb_bram_0/mb_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_lmb_bram_0 || ORIG_REF_NAME==mb_design_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_xbar_0/mb_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_xbar_0 || ORIG_REF_NAME==mb_design_xbar_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_periph_0/mb_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_axi_intc_0/mb_design_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_microblaze_0_xlconcat_0/mb_design_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_mdm_1_0/mb_design_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_mdm_1_0 || ORIG_REF_NAME==mb_design_mdm_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_clk_wiz_1_0/mb_design_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_0 || ORIG_REF_NAME==mb_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_0/mb_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_0_0/mb_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_0 || ORIG_REF_NAME==mb_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_1_0/mb_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_1_0 || ORIG_REF_NAME==mb_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_2_0/mb_design_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_2_0 || ORIG_REF_NAME==mb_design_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_gpio_3_0/mb_design_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_3_0 || ORIG_REF_NAME==mb_design_axi_gpio_3_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_uartlite_0_0/mb_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_uartlite_0_0 || ORIG_REF_NAME==mb_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_timer_0_0/mb_design_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_timer_0_0 || ORIG_REF_NAME==mb_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_fit_timer_0_0/mb_design_fit_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_fit_timer_0_0 || ORIG_REF_NAME==mb_design_fit_timer_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_dma_0_0/mb_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_dma_0_0 || ORIG_REF_NAME==mb_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axis_data_fifo_0_0/mb_design_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axis_data_fifo_0_0 || ORIG_REF_NAME==mb_design_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_axi_emc_0_1/mb_design_axi_emc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_emc_0_1 || ORIG_REF_NAME==mb_design_axi_emc_0_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_AESEncrypter128Cop_0_0/mb_design_AESEncrypter128Cop_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_AESEncrypter128Cop_0_0 || ORIG_REF_NAME==mb_design_AESEncrypter128Cop_0_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_8/mb_design_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_8 || ORIG_REF_NAME==mb_design_auto_pc_8} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_0/mb_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_0 || ORIG_REF_NAME==mb_design_auto_pc_0} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_1/mb_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_1 || ORIG_REF_NAME==mb_design_auto_pc_1} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_2/mb_design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_2 || ORIG_REF_NAME==mb_design_auto_pc_2} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_3/mb_design_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_3 || ORIG_REF_NAME==mb_design_auto_pc_3} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_4/mb_design_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_4 || ORIG_REF_NAME==mb_design_auto_pc_4} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_5/mb_design_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_5 || ORIG_REF_NAME==mb_design_auto_pc_5} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_6/mb_design_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_6 || ORIG_REF_NAME==mb_design_auto_pc_6} -quiet] -quiet

# IP: bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_auto_pc_7 || ORIG_REF_NAME==mb_design_auto_pc_7} -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_microblaze_0_0/mb_design_microblaze_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_0 || ORIG_REF_NAME==mb_design_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_microblaze_0_0/mb_design_microblaze_0_0_ooc_debug.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_lmb_bram_0/mb_design_lmb_bram_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_microblaze_0_axi_intc_0/mb_design_microblaze_0_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_microblaze_0_axi_intc_0/mb_design_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_design_microblaze_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_microblaze_0_axi_intc_0/mb_design_microblaze_0_axi_intc_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_mdm_1_0/mb_design_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_mdm_1_0 || ORIG_REF_NAME==mb_design_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_mdm_1_0/mb_design_mdm_1_0_ooc_trace.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_clk_wiz_1_0/mb_design_clk_wiz_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_0 || ORIG_REF_NAME==mb_design_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_clk_wiz_1_0/mb_design_clk_wiz_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_clk_wiz_1_0 || ORIG_REF_NAME==mb_design_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_clk_wiz_1_0/mb_design_clk_wiz_1_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_0/mb_design_rst_clk_wiz_1_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_design_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_rst_clk_wiz_1_100M_0/mb_design_rst_clk_wiz_1_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_design_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_0/mb_design_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_0 || ORIG_REF_NAME==mb_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_0/mb_design_axi_gpio_0_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_0/mb_design_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_0_0 || ORIG_REF_NAME==mb_design_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_1_0/mb_design_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_1_0 || ORIG_REF_NAME==mb_design_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_1_0/mb_design_axi_gpio_1_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_1_0/mb_design_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_1_0 || ORIG_REF_NAME==mb_design_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_2_0/mb_design_axi_gpio_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_2_0 || ORIG_REF_NAME==mb_design_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_2_0/mb_design_axi_gpio_2_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_2_0/mb_design_axi_gpio_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_2_0 || ORIG_REF_NAME==mb_design_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_3_0/mb_design_axi_gpio_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_3_0 || ORIG_REF_NAME==mb_design_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_3_0/mb_design_axi_gpio_3_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_gpio_3_0/mb_design_axi_gpio_3_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_gpio_3_0 || ORIG_REF_NAME==mb_design_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_uartlite_0_0/mb_design_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_uartlite_0_0 || ORIG_REF_NAME==mb_design_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_uartlite_0_0/mb_design_axi_uartlite_0_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_uartlite_0_0/mb_design_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_uartlite_0_0 || ORIG_REF_NAME==mb_design_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_timer_0_0/mb_design_axi_timer_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_timer_0_0 || ORIG_REF_NAME==mb_design_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_timer_0_0/mb_design_axi_timer_0_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_dma_0_0/mb_design_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_dma_0_0 || ORIG_REF_NAME==mb_design_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_dma_0_0/mb_design_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mb_design_axi_dma_0_0 || ORIG_REF_NAME==mb_design_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_emc_0_1/mb_design_axi_emc_0_1_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_emc_0_1 || ORIG_REF_NAME==mb_design_axi_emc_0_1} -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_emc_0_1/mb_design_axi_emc_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_design_axi_emc_0_1 || ORIG_REF_NAME==mb_design_axi_emc_0_1} -quiet] -quiet

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_axi_emc_0_1/mb_design_axi_emc_0_1_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_8/mb_design_auto_pc_8_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_0/mb_design_auto_pc_0_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_1/mb_design_auto_pc_1_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_2/mb_design_auto_pc_2_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_3/mb_design_auto_pc_3_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_4/mb_design_auto_pc_4_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_5/mb_design_auto_pc_5_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_6/mb_design_auto_pc_6_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/ip/mb_design_auto_pc_7/mb_design_auto_pc_7_ooc.xdc

# XDC: c:/Xilinx/projects/CR_AES128_Proj/MB_DMA_Base/MB_DMA_Base.gen/sources_1/bd/mb_design/mb_design_ooc.xdc
