using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GLUA_DB
{
    /// <summary>
    /// Interaction logic for PCs.xaml
    /// </summary>
    public partial class PCs : Page
    {
        public PCs()
        {
            void PCsDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
            {
                PCsDataGrid.Columns[0].Visibility = Visibility.Hidden;
            }

            InitializeComponent();
            PCsDataGrid.AutoGeneratedColumns += PCsDataGrid_AutoGeneratedColumns;
            PCsDataGrid.ItemsSource = getPCsList();
        }

        public void Row_DoubleClick(object sender, MouseButtonEventArgs e)
        {
            DataGridRow row = ItemsControl.ContainerFromElement((DataGrid)sender,
                                        e.OriginalSource as DependencyObject) as DataGridRow;

            if (row == null) return;
            PC rowPage = new PC((int)(((DataRowView)row.Item).Row["ID"]));
            this.NavigationService.Navigate(rowPage);
        }

        public static DataView getPCsList()
        {
            string queryString =
                "SELECT * FROM dbo.PCs";

            using (SqlConnection cn = new SqlConnection(DB.getDB().getConnectionString()))
            {
                using (var cmd = new SqlCommand(queryString, cn))
                {
                    cn.Open();
                    var reader = cmd.ExecuteReader();

                    var dt = new DataTable();

                    DataColumn[] dc = new DataColumn[] { new DataColumn("ID", typeof(int)), new DataColumn("Fabricante", typeof(string)), new DataColumn("Modelo", typeof(string)), new DataColumn("Tempo Despendido", typeof(string)), new DataColumn("Num de Atendimentos", typeof(string))};
                    dt.Columns.AddRange(dc);

                    while (reader.Read())
                    {
                        DataRow row = dt.NewRow();
                        row["ID"] = Convert.ToInt32(reader["ID"]);
                        row["Fabricante"] = reader["Fabricante"].ToString();
                        row["Modelo"] = reader["Modelo"].ToString();
                        if (!(row["Tempo Despendido"] is DBNull)) row["Tempo Despendido"] = DB.getSpentTime(Convert.ToInt32(reader["Tempo_despendido"].ToString()));
                        else row["Tempo Despendido"] = "0h00";
                        row["Num de Atendimentos"] = reader["num_vistos"].ToString();
                        dt.Rows.Add(row);
                    }

                    return dt.DefaultView;
                }
            }
        }

        private void InsertPC_Click(object sender, RoutedEventArgs e)
        {
            PC rowPage = new PC(-1);
            this.NavigationService.Navigate(rowPage);
        }
    }
}
