using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GLUA_DB
{
    /// <summary>
    /// Interaction logic for Sessoes.xaml
    /// </summary>
    public partial class Sessoes : Page
    {
        public Sessoes()
        {
            void SistemasOpsGrid_AutoGeneratedColumns(object sender, EventArgs e)
            {
                SessoesDataGrid.Columns[0].Visibility = Visibility.Hidden;
            }

            InitializeComponent();
            SessoesDataGrid.AutoGeneratedColumns += SistemasOpsGrid_AutoGeneratedColumns;
            SessoesDataGrid.ItemsSource = getSessoesList();
        }

        private DataView getSessoesList()
        {
            string queryString =
                "SELECT * FROM dbo.SESSOES ORDER BY Data DESC;";

            using (SqlConnection cn = new SqlConnection(DB.getDB().getConnectionString()))
            {
                using (var cmd = new SqlCommand(queryString, cn))
                {
                    cn.Open();
                    var reader = cmd.ExecuteReader();

                    var dt = new DataTable();

                    DataColumn[] dc = new DataColumn[] { new DataColumn("ID", typeof(int)), new DataColumn("Data", typeof(string)), new DataColumn("Local", typeof(string)), new DataColumn("Num de Previstos", typeof(int)), new DataColumn("Num de Atendimentos", typeof(int)), new DataColumn("Num de Membros", typeof(int)) };
                    dt.Columns.AddRange(dc);

                    while (reader.Read())
                    {
                        DataRow row = dt.NewRow();
                        row["ID"] = Convert.ToInt32(reader["ID"]);
                        row["Data"] = reader["Data"].ToString();
                        row["Local"] = reader["Local"].ToString();
                        row["Num de Previstos"] = Convert.ToInt32(reader["Num_previstos"]);
                        row["Num de Atendimentos"] = Convert.ToInt32(reader["atendimentos_num"]);
                        row["Num de Membros"] = Convert.ToInt32(reader["membros_num"]);
                        dt.Rows.Add(row);
                    }

                    return dt.DefaultView;
                }
            }
        }

        private void Row_DoubleClick(object sender, MouseButtonEventArgs e)
        {
            DataGridRow row = ItemsControl.ContainerFromElement((DataGrid)sender,
                                        e.OriginalSource as DependencyObject) as DataGridRow;

            if (row == null) return;
            Sessao rowPage = new Sessao((int)(((DataRowView)row.Item).Row["ID"]));
            this.NavigationService.Navigate(rowPage);
        }

        private void InsertAtendimento_Click(object sender, RoutedEventArgs e)
        {
            Sessao rowPage = new Sessao(-1);
            this.NavigationService.Navigate(rowPage);
        }
    }
}
