using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GLUA_DB
{
    /// <summary>
    /// Interaction logic for SistemasOps.xaml
    /// </summary>
    public partial class SistemasOps : Page
    {
        public SistemasOps()
        {
            void SistemasOpsGrid_AutoGeneratedColumns(object sender, EventArgs e)
            {
                SistemasOpsGrid.Columns[0].Visibility = Visibility.Hidden;
            }

            InitializeComponent();
            SistemasOpsGrid.AutoGeneratedColumns += SistemasOpsGrid_AutoGeneratedColumns;
            SistemasOpsGrid.ItemsSource = getSistemasList();
        }

        private DataView getSistemasList()
        {
            string queryString =
                "SELECT * FROM SistemasOperativos ORDER BY Nome ASC;";

            using (SqlConnection cn = new SqlConnection(DB.getDB().getConnectionString()))
            {
                using (var cmd = new SqlCommand(queryString, cn))
                {
                    cn.Open();
                    var reader = cmd.ExecuteReader();

                    var dt = new DataTable();

                    DataColumn[] dc = new DataColumn[] { new DataColumn("id", typeof(int)), new DataColumn("Nome", typeof(string)), new DataColumn("Versao", typeof(string)), new DataColumn("Num de Flash Drives", typeof(string)), new DataColumn("Num de Problemas", typeof(string)) };
                    dt.Columns.AddRange(dc);

                    while (reader.Read())
                    {
                        DataRow row = dt.NewRow();
                        row["ID"] = Convert.ToInt32(reader["ID"]);
                        row["Nome"] = reader["Nome"].ToString();
                        row["Versao"] = reader["Versao"].ToString();
                        row["Num de Flash Drives"] = reader["flashDrives_num"].ToString();
                        row["Num de Problemas"] = reader["problems_num"].ToString();
                        dt.Rows.Add(row);
                    }

                    return dt.DefaultView;
                }
            }
        }

        private void SistemasOpsGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            DataGridRow row = ItemsControl.ContainerFromElement((DataGrid)sender,
                                        e.OriginalSource as DependencyObject) as DataGridRow;

            if (row == null) return;
            SistemaOp rowPage = new SistemaOp((int)(((DataRowView)row.Item).Row["ID"]));
            this.NavigationService.Navigate(rowPage);
        }

        private void InsertOS_Click(object sender, RoutedEventArgs e)
        {
            SistemaOp rowPage = new SistemaOp(-1);
            this.NavigationService.Navigate(rowPage);
        }
    }
}
