using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GLUA_DB
{
    /// <summary>
    /// Interaction logic for Topicos.xaml
    /// </summary>
    public partial class Topicos : Page
    {
        public Topicos()
        {
            void SistemasOpsGrid_AutoGeneratedColumns(object sender, EventArgs e)
            {
                TopicosGrid.Columns[0].Visibility = Visibility.Hidden;
            }

            InitializeComponent();
            TopicosGrid.AutoGeneratedColumns += SistemasOpsGrid_AutoGeneratedColumns;
            TopicosGrid.ItemsSource = getTopicosList();
        }

        private DataView getTopicosList()
        {
            string queryString =
                "SELECT * FROM TOPICOS ORDER BY problemas_num DESC;";

            using (SqlConnection cn = new SqlConnection(DB.getDB().getConnectionString()))
            {
                using (var cmd = new SqlCommand(queryString, cn))
                {
                    cn.Open();
                    var reader = cmd.ExecuteReader();

                    var dt = new DataTable();

                    DataColumn[] dc = new DataColumn[] { new DataColumn("ID", typeof(int)), new DataColumn("Nome", typeof(string)), new DataColumn("Num de problemas", typeof(int)) };
                    dt.Columns.AddRange(dc);

                    while (reader.Read())
                    {
                        DataRow row = dt.NewRow();
                        row["ID"] = Convert.ToInt32(reader["ID"]);
                        row["Nome"] = reader["Nome"].ToString();
                        row["Num de problemas"] = Convert.ToInt32(reader["problemas_num"]);
                        dt.Rows.Add(row);
                    }

                    return dt.DefaultView;
                }
            }
        }

        private void TopicosGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            DataGridRow row = ItemsControl.ContainerFromElement((DataGrid)sender,
                                        e.OriginalSource as DependencyObject) as DataGridRow;

            if (row == null) return;
            Topico rowPage = new Topico((int)(((DataRowView)row.Item).Row["ID"]));
            this.NavigationService.Navigate(rowPage);
        }

        private void InsertTopic_Click(object sender, RoutedEventArgs e)
        {
            Topico rowPage = new Topico(-1);
            this.NavigationService.Navigate(rowPage);
        }
    }
}
