using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace GLUA_DB
{
    /// <summary>
    /// Interaction logic for Utentes.xaml
    /// </summary>
    public partial class Utentes : Page
    {
        public Utentes()
        {
            void MembrosDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
            {
                UtentesDataGrid.Columns[0].Visibility = Visibility.Hidden;
            }

            InitializeComponent();
            UtentesDataGrid.AutoGeneratedColumns += MembrosDataGrid_AutoGeneratedColumns;
            UtentesDataGrid.ItemsSource = getUtentesList("", "");
            Filter_ComboBox.SelectedIndex = 0;
        }

        public void Row_DoubleClick(object sender, MouseButtonEventArgs e)
        {
            DataGridRow row = ItemsControl.ContainerFromElement((DataGrid)sender,
                                        e.OriginalSource as DependencyObject) as DataGridRow;

            if (row == null) return;
            Console.WriteLine(((DataRowView)row.Item).Row["ID"]);
            Utente rowPage = new Utente((int)(((DataRowView)row.Item).Row["ID"]));
            this.NavigationService.Navigate(rowPage);
        }

        private void InsertUtente_Click(object sender, RoutedEventArgs e)
        {
            Utente Page = new Utente(-1);
            this.NavigationService.Navigate(Page);
        }

        private DataView getUtentesList(string column, string value)
        {
            string queryString =
                "SELECT Pessoa.ID as ID, Nome, Contacto, Notas FROM Utente JOIN Pessoa ON Utente.ID = Pessoa.ID";

            if (column.Length != 0 && value.Length != 0) queryString += " WHERE "+column+" LIKE @value;"; 

            using (SqlConnection cn = new SqlConnection(DB.getDB().getConnectionString()))
            {
                using (var cmd = new SqlCommand(queryString, cn))
                {
                    cn.Open();
                    cmd.Parameters.AddWithValue("@column", column);
                    cmd.Parameters.AddWithValue("@value", value+"%");
                    var reader = cmd.ExecuteReader();
                    

                   var dt = new DataTable();

                    DataColumn[] dc = new DataColumn[] { new DataColumn("ID", typeof(int)), new DataColumn("Nome", typeof(string)), new DataColumn("Contacto", typeof(string)), new DataColumn("Notas", typeof(string)) };
                    dt.Columns.AddRange(dc);

                    while (reader.Read())
                    {
                        DataRow row = dt.NewRow();
                        row["ID"] = Convert.ToInt32(reader["ID"]);
                        row["Nome"] = reader["Nome"].ToString();
                        row["Contacto"] = reader["Contacto"].ToString();
                        if (row["Contacto"].Equals("")) row["Contacto"] = "///////////////";

                        row["Notas"] = reader["Notas"].ToString();
                        dt.Rows.Add(row);
                    }

                    return dt.DefaultView;
                }
            }
        }

        private void Filter_ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (Filter_TextBox.Text.Length != 0) UtentesDataGrid.ItemsSource = getUtentesList(Filter_ComboBox.SelectedValue.ToString(), Filter_TextBox.Text);
        }

        private void Filter_TextBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            if(Filter_ComboBox.SelectedItem != null) UtentesDataGrid.ItemsSource = getUtentesList(Filter_ComboBox.SelectedValue.ToString(), Filter_TextBox.Text);
        }
    }
}
